### ISSUE TITLE
Missing SQL

### ISSUE THREAD

**Issue by moos3** [laurencedawson/embr#12]
The installation process is missing the SQL for mysql. Right now a fresh installation just whitescreens. Help please.

**Comment by laurencedawson** [comment]
Hi there, the SQL is contained in the file /application/models/setup_model.php

Provided you entered your database details correctly into the database config file, it should automatically setup the db for you. Let me know if it works!

**Comment by moos3** [comment]
Fatal error: Call to a member function num_rows() on a non-object in /Users/moose/srv_backup/blog/embr/system/database/drivers/mysql/mysql_driver.php on line 381

Getting this. Ideas ?

**Comment by yangboz** [comment]
Mark the same problem .

**Comment by laurencedawson** [comment]
I'll take a look into this, thanks guys!
