### ISSUE TITLE
where is the mysql database script?

### ISSUE THREAD

**Issue by jiji262** [laurencedawson/embr#14]
I didn;t find it in the tarball, could you tell me where to find it?

**Comment by inverse** [comment]
The database is generated in the model. The database checked in the default Blog Controller during construction

Check out:

 application /models /setup_model.php

**Comment by laurencedawson** [comment]
Thanks Mal. As this has been raised several times, I will look to include an alternative method to instantiate and populate the DB.

**Comment by jiji262** [comment]
1. download CodeIgniter_2.1.0.zip from codeigniter offical site and unzip it. Assume the directory name you have changed to Embr.
2. download embr tarball and unzip to replace the coresponding files in "application" directory, and also copy the new added directories to "embr", such as img, js, themes.
3. download template library from http://williamsconcepts.com/ci/codeigniter/libraries/template/Template_1.4.1.zip, and copy the library directory to replace the libray directory in "application".
4. set the database user and password, change the file application/config/database.php.
5. set the admin info, change the file application/config/blog.php.

Please make sure in the database there is no database named "blog". The program will create database and tables automatically when the website is first visited.
