### ISSUE TITLE
Trouble with the setup....

### ISSUE THREAD

**Issue by zer01ne** [laurencedawson/embr#15]
The install script doesn't exactly work anymore due to dead links, however, I did manage to manually install embr over a fresh 2.0.2 CI download and install/configure template.. (i think correctly).  Anyhow, http://www.zimagez.com/zimage/screenshot-122011-200528.php is what I am getting now.  Nothing works either.  Any assistance would be great.  

I can also pastebin all of the files if you would like to see them.

**Comment by zer01ne** [comment]
short tags.....

**Comment by jiji262** [comment]
1. download CodeIgniter_2.1.0.zip from codeigniter offical site and unzip it. Assume the directory name you have changed to Embr.
2. download embr tarball and unzip to replace the coresponding files in "application" directory, and also copy the new added directories to "embr", such as img, js, themes.
3. download template library from http://williamsconcepts.com/ci/codeigniter/libraries/template/Template_1.4.1.zip, and copy the library directory to replace the libray directory in "application".
4. set the database user and password, change the file application/config/database.php.
5. set the admin info, change the file application/config/blog.php.

Please make sure in the database there is no database named "blog". The program will create database and tables automatically when the website is first visited.
