### ISSUE TITLE
404 error when creating new post

### ISSUE THREAD

**Issue by joelkuehn** [laurencedawson/embr#16]
First of all, thank you for developing this. I am looking forward to using it.

I have run the installer and can login to the admin.  When I create a new post (of any type), upon submit it redirects to a friendly url (http://localhost:8888/embr/test-entry-title) but that page does not exist.  Nothing is stored in the database. 

I can add an entry manually in the database and it appears on the site.

Could you please advise?
Thank you.

**Comment by laurencedawson** [comment]
Hmm, sounds like the a database issue, can you confirm the details in database.php are correct?

**Comment by joelkuehn** [comment]
Thank you for looking into this.

The details below are confirmed correct. There is an 'embr' database created, but even with the active group set to 'default', the front end of the site is pulling data from 'blog'.

The 'blog' database was populated with the install.sh info, and this info below was created when running that install script.

Did I miss a config setting in another place?

---

$active_group = 'default';
$active_record = TRUE;

$db['default']['hostname'] = 'localhost';
$db['default']['username'] = 'root';
$db['default']['password'] = 'root';
$db['default']['database'] = 'embr';
$db['default']['dbdriver'] = 'mysql';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = FALSE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
$db['default']['swap_pre'] = '';
$db['default']['autoinit'] = FALSE;
$db['default']['stricton'] = FALSE;

$db['blog']['hostname'] = $db['default']['hostname'];
$db['blog']['username'] = $db['default']['username'];
$db['blog']['password'] = $db['default']['password'];
$db['blog']['database'] = 'blog';
$db['blog']['dbdriver'] = $db['default']['dbdriver'];
$db['blog']['dbprefix'] = $db['default']['dbprefix'];
$db['blog']['pconnect'] = FALSE;
$db['blog']['db_debug'] = $db['default']['db_debug'];
$db['blog']['cache_on'] = FALSE;
$db['blog']['cachedir'] = './application/cache';
$db['blog']['char_set'] = $db['default']['char_set'];
$db['blog']['dbcollat'] = $db['default']['dbcollat'];
$db['blog']['swap_pre'] = $db['default']['swap_pre'];
$db['blog']['autoinit'] = $db['default']['autoinit'];
$db['blog']['stricton'] = $db['default']['stricton'];

**Comment by shealy2010** [comment]
Hello,
I've experienced the exact issue as joelkuehn reported. Has a resolution or workaround been reached?

Thank you, Laurence! Your blog looks very promising.

**Comment by shealy2010** [comment]
In my case, the posted $data array was not able to insert into the 'blog' table because 'blog', as it is, does not allow for Null. Try changing image, summary, comments, (publish?) & source fields in 'blog' table to allow for Null. This worked for me.

**Comment by joelkuehn** [comment]
This fix worked for me, as well. 

I changed all fields except id and datet to Allow Null.

Thanks, @shealy2010

**Comment by laurencedawson** [comment]
Ha nice one, cheers shealy2010!
